### ISSUE TITLE
No se cumple lineamiento OAS de nombres de repo

### ISSUE THREAD

**Issue by jjvargass** [udistrital/ss_crud_api#5]
se debe cumplir con los lineamientos definidos en el siguiente link:

https://github.com/udistrital/introduccion_oas/blob/master/repositorios_institucionales/lineamientos.md

para el caso: seguridad_social_crud

**Comment by juancsr** [comment]
Se creo un nuevo repositorio cuyo nombre cumple con los lineamientos establecidos.

El nuevo respositorio se encuentra en este link:
https://github.com/udistrital/seguridad_social_crud

se cierra el issue.
